import { AlertTriangle, Check, ChevronRight, Cloud, CloudOff, Database, Download, FlaskConical, RotateCcw, Settings2, ShieldAlert, Upload } from 'lucide-react';
import { usePrototypeStore } from '../adapters/PrototypeStore.jsx';
import { navigate } from '../app/router.js';
import { MODEL_ID, money } from '../model/riskModel.js';
import { Button, Card, Eyebrow, SectionHeading, StatusPill, formatRelativeTime } from '../ui/primitives.jsx';

function SettingRow({ icon, title, detail, children }) {
  return <div className="setting-row">{icon}<div className="setting-row__copy"><strong>{title}</strong><span>{detail}</span></div>{children}</div>;
}

function SyncDetail() {
  const { state, actions } = usePrototypeStore();
  const attention = state.records.filter((record) => ['queued', 'failed', 'conflict'].includes(record.syncState) && !record.deleted);
  return <>
    <Card className="sync-hero"><div><Eyebrow>Simulated remote continuity</Eyebrow><h2>{state.network === 'offline' ? 'Offline - changes remain here' : state.sync.phase === 'failed' ? 'Retry required' : attention.length ? `${attention.length} records need continuity` : 'Device ledger is clear'}</h2></div><StatusPill state={state.network === 'offline' ? 'offline' : state.sync.phase === 'checking' ? 'checking' : state.sync.phase === 'failed' ? 'failed' : attention.length ? attention[0].syncState : 'verified'}>{state.sync.phase === 'checking' ? 'Checking' : state.network}</StatusPill><Button onClick={actions.syncNow} disabled={state.sync.phase === 'checking'}>{state.sync.phase === 'checking' ? 'Checking...' : 'Check now'}</Button></Card>
    <Card className="sync-timestamps"><div><span>Last checked</span><strong>{formatRelativeTime(state.sync.lastChecked)}</strong></div><div><span>Last uploaded</span><strong>{formatRelativeTime(state.sync.lastUploaded)}</strong></div><div><span>Last merged</span><strong>{formatRelativeTime(state.sync.lastMerged)}</strong></div></Card>
    <section><h2 className="list-heading">Record continuity</h2><div className="sync-record-list">{attention.length ? attention.map((record) => <Card key={record.uid} className="sync-record"><div><strong>Trade {record.displayId} · {record.instrument}</strong><span>revision {record.revision} · stable UID</span></div><StatusPill state={record.syncState}>{record.syncState}</StatusPill>{record.syncState === 'conflict' && <Button variant="secondary" onClick={() => actions.resolveConflict(record.uid)}>Keep this device revision</Button>}</Card>) : <Card className="sync-record sync-record--empty"><Check aria-hidden="true" /><span>No record is waiting, failed, or conflicted.</span></Card>}</div></section>
    <Card className="prototype-disclosure"><FlaskConical aria-hidden="true" /><div><h2>Network behavior is simulated</h2><p>No request reaches Cloudflare, the production Worker, or another device. This screen demonstrates truth states and recovery interaction only.</p></div></Card>
  </>;
}

function SystemHome() {
  const { state, stats, actions } = usePrototypeStore();
  const pending = state.records.filter((record) => ['queued', 'failed', 'conflict'].includes(record.syncState) && !record.deleted).length;
  const deletedRecords = state.records.filter((record) => record.deleted);
  return <>
    <section className="settings-group"><h2>Continuity</h2><Card className="settings-card"><button className="setting-link" onClick={() => navigate('/prototype/system/sync')}><Cloud aria-hidden="true" /><div><strong>Sync and storage</strong><span>{pending ? `${pending} records need attention` : 'No pending record changes'} · checked {formatRelativeTime(state.sync.lastChecked)}</span></div><ChevronRight aria-hidden="true" /></button><SettingRow icon={state.network === 'offline' ? <CloudOff aria-hidden="true" /> : <Cloud aria-hidden="true" />} title="Connection fixture" detail="Controls the deterministic offline/reconnect state."><Button variant="secondary" onClick={() => actions.setNetwork(state.network === 'offline' ? 'online' : 'offline')}>Go {state.network === 'offline' ? 'online' : 'offline'}</Button></SettingRow></Card></section>
    <section className="settings-group"><h2>Model authority</h2><Card className="settings-card"><SettingRow icon={<Database aria-hidden="true" />} title={MODEL_ID} detail={`Strategy equity ${money(stats.equity)} · gross 1:1`}><StatusPill state="verified">Canonical</StatusPill></SettingRow><div className="setting-explainer">Sizing uses strategy equity, not exchange wallet, available margin, or cross collateral. Execution snapshots never change after recording.</div></Card></section>
    <section className="settings-group"><h2>Risk controls</h2><Card className="settings-card"><SettingRow icon={<ShieldAlert aria-hidden="true" />} title="Daily-loss warning" detail="Warns; it does not block exchange execution."><input className="switch" type="checkbox" aria-label="Daily-loss warning" checked={state.settings.dailyLossWarning} onChange={(event) => actions.updateSetting('dailyLossWarning', event.target.checked)} /></SettingRow><SettingRow icon={<AlertTriangle aria-hidden="true" />} title="Loss-streak review" detail="Requests review after three consecutive losses."><input className="switch" type="checkbox" aria-label="Loss-streak review" checked={state.settings.lossStreakReview} onChange={(event) => actions.updateSetting('lossStreakReview', event.target.checked)} /></SettingRow><SettingRow icon={<Settings2 aria-hidden="true" />} title="Large planned-risk acknowledgement" detail={`Acknowledge above ${money(state.settings.maxPlannedRiskAcknowledgement)}; canonical sizing is unchanged.`}><span className="setting-value">{money(state.settings.maxPlannedRiskAcknowledgement)}</span></SettingRow></Card></section>
    <section className="settings-group"><h2>Display and access</h2><Card className="settings-card"><SettingRow icon={<Settings2 aria-hidden="true" />} title="Reduced motion" detail="Default off. Removes nonessential transforms and ceremony."><input className="switch" type="checkbox" aria-label="Reduced motion" checked={state.settings.reducedMotion} onChange={(event) => actions.updateSetting('reducedMotion', event.target.checked)} /></SettingRow><SettingRow icon={<Settings2 aria-hidden="true" />} title="Large text review mode" detail="Default off. Exercises wrapping and control resilience."><input className="switch" type="checkbox" aria-label="Large text review mode" checked={state.settings.largeText} onChange={(event) => actions.updateSetting('largeText', event.target.checked)} /></SettingRow><div className="setting-explainer"><Button variant="secondary" onClick={actions.resetSettings}><RotateCcw aria-hidden="true" /> Reset controls to defaults</Button></div></Card></section>
    <section className="settings-group"><h2>Data tools</h2><Card className="settings-card"><button className="setting-link" onClick={() => alert('Prototype export preview: records, tombstones, model snapshots, settings, fixture checksum. No file was downloaded.')}><Download aria-hidden="true" /><div><strong>Preview export manifest</strong><span>Simulation only · no backup claim</span></div><ChevronRight aria-hidden="true" /></button><button className="setting-link" onClick={() => alert('Prototype import preview validates schema and counts but cannot import production data.')}><Upload aria-hidden="true" /><div><strong>Preview import validation</strong><span>Simulation only · no production write</span></div><ChevronRight aria-hidden="true" /></button></Card></section>
    {deletedRecords.length > 0 && <section className="settings-group"><h2>Prototype recovery</h2><Card className="settings-card">{deletedRecords.map((record) => <SettingRow key={record.uid} icon={<RotateCcw aria-hidden="true" />} title={`Trade ${record.displayId} · ${record.instrument}`} detail="Tombstoned locally; recovery is prototype-only."><Button variant="secondary" onClick={() => actions.recoverDeletedTrade(record.uid)}>Recover</Button></SettingRow>)}</Card></section>}
    <section className="settings-group"><h2>Prototype</h2><Card className="settings-card"><button className="setting-link" onClick={() => navigate('/prototype/review')}><FlaskConical aria-hidden="true" /><div><strong>Review harness</strong><span>Switch deterministic scenarios and reset isolated data</span></div><ChevronRight aria-hidden="true" /></button><button className="setting-link setting-link--danger" onClick={() => window.confirm('Reset this isolated fixture and discard its prototype-only changes?') && actions.resetScenario(state.scenarioId)}><RotateCcw aria-hidden="true" /><div><strong>Reset current fixture</strong><span>Deletes only isolated prototype changes</span></div><ChevronRight aria-hidden="true" /></button></Card></section>
  </>;
}

export default function System({ route }) {
  const syncDetail = route.pathname.endsWith('/sync');
  return <main className="page" id="main-content"><SectionHeading eyebrow="System truth" title={syncDetail ? 'Sync detail' : 'System'} action={syncDetail ? <Button variant="quiet" onClick={() => navigate('/prototype/system')}>All settings</Button> : undefined} />{syncDetail ? <SyncDetail /> : <SystemHome />}</main>;
}
